tasks/urls.py
from django.urls import path, include
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='all_tasks'),
    path('<int:pk>', views.TaskDetailView.as_view(), name='task_detail'),
    path('<int:pk>/delete', views.TaskDeleteView.as_view(), name='task_delete'),
    path('<int:pk>/update', views.TaskUpdateView.as_view(), name='task_update'),
    path('new', views.TaskCreateView.as_view(), name='new_task'),
]

tasks/models.py
import django.utils.timezone
from django.db import models
from django.urls import reverse_lazy

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(default=django.utils.timezone.now())

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('tasks:all_tasks')

tasks/forms.py
from django.forms import ModelForm
from .models import Task
from django import forms

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title','body','deadline']

tasks/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from .forms import TaskForm
from .models import Task


# Create your views here.
# CRUD => CREATE READ UPDATE DELETE
class TaskListView(generic.ListView):
    model = Task
    template_name = 'tasks/all_tasks.html'
    context_object_name = 'tasks'


class TaskDetailView(generic.DetailView):
    model = Task
    template_name = 'tasks/task_detail.html'
    context_object_name = 'task'


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:all_tasks')
    template_name = 'tasks/task_delete.html'


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/new_task.html'


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/task_update.html'

tasks/templates/tasks/all_tasks.html
{% extends 'tasks/base.html' %}

{% block content %}
    {% if tasks is null %}
        {% for task in tasks %}
            <div>
                <h2>{{task.title}}</h2><br>
                <p>Yangi: {{task.created_at}}</p>
                <a href="{% url 'tasks:task_detail' task.pk %}">Korish</a>
            </div>
        {% endfor %}
    {% else %}

    <p>Qlinadigon ishalar yoq</p>
    {% endif %}
{% endblock %}

tasks/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>Todo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/page.css'%}">
</head>
<body>
<h1><a href="{% url 'tasks:all_tasks' %}">Qilish kerak bolgan ish</a></h1>
    <a href="{% url 'tasks:new_task' %}">Yangi ish qoshish</a>
    <hr>
    {% block content%}
    {% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

tasks/templates/tasks/new_task.html
{% extends 'tasks/base.html' %}

{% block content %}
<h2>Yangi ish</h2>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save">
</form>
{% endblock %}

tasks/templates/tasks/task_delete.html
{% extends 'tasks/base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <label>Ochirish</label>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

tasks/templates/tasks/task_detail.html
{% extends 'tasks/base.html' %}
{% load static %}
{% block content %}
            <div>
                <h2>{{task.title}}</h2><br>
                <p>{{task.body}}</p>
                <p>yaratish: {{task.created_at}}</p>
                <p>Deadline: {{task.deadline}}</p>
                <a href="{% url 'tasks:task_update' task.pk %}">sozlash</a>
                <a href="{% url 'tasks:task_delete' task.pk %}">ochirish</a>
            </div>
{% endblock %}

tasks/templates/tasks/task_update.html
{% extends 'tasks/base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h3> {{form.title}} </h3>
    <input type="submit" value="Save">
</form>
{% endblock %}